package dev.mcger.protocol;

public enum MessageType {
  WORLD_LIST_REQUEST,
  WORLD_CREATE_REQUEST,
  WORLD_JOIN_REQUEST,
  WORLD_SEARCH_REQUEST,
  WORLD_DELETE_REQUEST,
  WORLD_UPDATE_STATUS_REQUEST,
  WORLD_UPDATE_CONFIG_REQUEST
}
